### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by kerko**
Just some minor rewording and spelling fixes
Signed-off-by: Jan Kerkenhoff <jan.kerkenhoff@braintags.de>

### CODE REVIEW

**Comment by pmlopes** [comment]
Sorry for the inconvenience but the asciidoc files are generated from:

https://github.com/vert-x3/vertx-circuit-breaker/blob/master/src/main/java/io/vertx/circuitbreaker/package-info.java

Would you mind to update your PR to reflect the changes there!

Thanks!

**Comment by kerko** [comment]
@pmlopes  I already did the changes in the `src/main/io/vertx/circuitbreaker/package-info.java`.
The other changes are just from regenerating the docs form the `package-info.java`.

**Comment by pmlopes** [comment]
Can we close this issue then?

**Comment by kerko** [comment]
@pmlopes No :smile: 
What I meant is, the initial pr already included the changes in `package-info.java`. So what you askes me to do, was already done. Thats why its 5 changed files:

**Pull request merged**
