### PR TITLE
#21: Implement support for retry policy

### PR DESCRIPTION
**Pull request by inikolaev**
The following changed have been made:
* Added usage example into `CircuitBreakerExamples`
* Added a new `retryPolicy` method to `CircuitBreaker` interface
* Created a new functional interface `RetryPolicy`. Originally I wanted to use `IntToLongFunction`, but as I understand it has to be whitelisted in `vertx-codegen`. I could also use `Function<Integer, Long>` I believe, but I wanted to avoid it because of unnecessary boxing and unboxing.
* Added a new private `executeRetryWithTimeout` method which executes retry with timeout if timeout is greater than 0
* Added a simple test which verifies that `RetryPolicy.getTimeout` has been called the required number of times.

Please have a look at the changes and let me know if I need to change or add anything else.

### CODE REVIEW

**Comment by cescoffier** [comment]
Looks good to me. Two small things:

* the documentation should contain a few sentence about the feature
* it needs to be tested against negative numbers

**Comment by vietj** [comment]
I believe you should be ok with a Function< Integer , Long> because in this case boxing will not be a performance issue and it avoids to introduce a specify type only for that.

**Comment by inikolaev** [comment]
@vietj I reverted `RetryPolicy` and replaced it with `Function<Integer, Long>`, please have a look.

@cescoffier regarding tests for negative and zero timeouts - I can add tests similar to one I created, since retry policy is being called all the time regardless of returned values, but this won't verify that indeed a different branch has been executed, unless there's a way to tell whether handler has been executed by timer or not. Would that be enough? I will add tests now and we can discuss later if necessary.

**Comment by inikolaev** [comment]
@cescoffier Added documentation, please have a look

**Comment by vietj** [comment]
@inikolaev looks good from this perspective, which makes me think we could support other function such as `IntFunction` in vertx code gen

**Comment by inikolaev** [comment]
@vietj I can create ticket and try to add it there then

**Comment by vietj** [comment]
@inikolaev it would be great, let's discuss it on the issue

**Comment by inikolaev** [comment]
@vietj is this ticket relevant to support `IntToLongFunction`: https://github.com/vert-x3/vertx-codegen/issues/104 ?

**Comment by vietj** [comment]
I think this issue is doing much more, I think what we can support easily are interfaces annotated with `@FunctionnalInterface` that are functions (i.e one parameter, one return type): `java.util.function.Function`, `IntToLongFunction`, etc...

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-codegen/issues/165

**Comment by inikolaev** [comment]
Should we merge this change if there are no more comments? 

I can make PR to incorporate `IntToLongFunction` once relevant change is merged into codegen, since that change would take a while for me to figure out all bits and pieces.

**Comment by inikolaev** [comment]
@vietj do you think this can be merged for now?

**Comment by thiagogcm** [comment]
Is this feature on the roadmap for next release?

**Comment by cescoffier** [comment]
Retry is supported by the circuit breaker. This PR is about improving the flexibility. Once the merge conflict is fixed, it can be merged.

**Comment by inikolaev** [comment]
@cescoffier I can take a look at it and rebase my changes on top of latest `master`

**Comment by inikolaev** [comment]
@cescoffier Already pushed fixes :)

**Comment by cescoffier** [comment]
Just a last check, did you sign the Eclipse CLA?

**Comment by inikolaev** [comment]
@cescoffier That's a good question - I don't recall.

**Comment by cescoffier** [comment]
@inikolaev On https://www.eclipse.org/legal/ECA.php you have links to sign and check if you already did (validation).

**Comment by inikolaev** [comment]
@cescoffier Have just signed it, you should be able to verify with my e-mail if needed

**Comment by cescoffier** [comment]
Thanks!

**Pull request merged**
